.catalog:
  name: Hadoop
  version: 2.7.1
  description: |
    Hadoop cluster.
  minimum_rancher_version: v0.59.0
  maintainer: "Prashant Pratap Singh <singh.pp7@gmail.com>"
  uuid: hadoop-0
  questions:
    - variable: "vcores_num"
      description: "yarn.nodemanager.resource.cpu-vcores"
      label: "Nodemanager cpu vcores:"
      required: true
      default: 4
      type: "int"
    - variable: "nm_mem"
      description: "yarn.nodemanager.resource.memory-mb"
      label: "Nodemanager resource memory in mb:"
      required: true
      default: 1024
      type: "int"
    - variable: "scheduler_min_mb"
      description: "yarn.scheduler.minimum-allocation-mb"
      label: "Scheduler Min Allocation in mb:"
      required: true
      default: 512
      type: "int"
    - variable: "log_agg"
      description: "yarn.log-aggregation-enable"
      label: "Log Aggregation required?:"
      required: true
      default: "true"
      type: "string"
    - variable: "map_mem"
      description: "mapreduce.map.memory.mb"
      label: "Map memory:"
      required: true
      default: 512
      type: "int"
    - variable: "reduce_mem"
      description: "mapreduce.reduce.memory.mb"
      label: "Reduce memory:"
      required: true
      default: 512
      type: "int"
    - variable: "map_opts"
      description: "mapreduce.map.java.opts"
      label: "Map java opts:"
      required: true
      default: "-Xmx512m"
      type: "string"
    - variable: "reduce_opts"
      description: "mapreduce.reduce.java.opts"
      label: "Reduce java opts:"
      required: true
      default: "-Xmx1024m"
      type: "string"
    - variable: "dfs_replication"
      description: "DFS replication"
      label: "dfs replication:"
      required: true
      default: 1
      type: "int"
namenode:
  scale: 1
secondarynamenode:
  scale: 1
datanode:
  scale: 1
resourcemanager:
  scale: 1
nodemanager:
  scale: 1
